% to plot the base functions


name = 'mlc';

z = mlcoors';   % n x #

% set a mtl file
fid = fopen(['data/base_texture.obj.mtl'],'w');
fprintf(fid,'# Generated by MATLAB\n');
fprintf(fid,'# Wavefront material file\n');
fprintf(fid,'newmtl material_0\n');
fprintf(fid,'Ka 0.200000 0.200000 0.200000\n');
fprintf(fid,'Kd 0.752941 0.752941 0.752941\n');
fprintf(fid,'Ks 1.000000 1.000000 1.000000\n');
fprintf(fid,'Tr 1.000000\n');
fprintf(fid,'illum 2\n');
fprintf(fid,'Ns 0.000000\n');
fprintf(fid,'map_Kd %s\n',[ './gbc_bar.png']);
fclose(fid);

load('colorbar_mlc.mat')
colorbar_mlc = colorbar_mlc(end:-1:1,:);
bar = colorbar_mlc';
bar= repmat(bar,500,1);
bar = reshape(bar,3,[]);
bar = reshape(bar,3,1,[]);
bar = permute(bar,[3 2 1]);
bar= repmat(bar,1,50);
imwrite(bar,['data/gbc_bar.png']);

% close(2)
for i = 1:size(z,2)

    bar_uv = [ones(length(xx),1)*0.5,z(:,i)];
    writeOBJ(['data/' name '_bf_' num2str(i) '.obj'],[xx 1-yy ...
        zeros(length(xx),1)],...
        tri(:,[4 3 2]),bar_uv);
    fid = fopen(['data/' name '_bf_' num2str(i) '.obj'],'a');
    fprintf(fid,['mtllib ./','base_texture.obj.mtl\n']);
    fclose(fid);


end